<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <FrameworkReference Include="Microsoft.AspNetCore.App" />
      <PackageReference Include="AWSSDK.S3" Version="4.0.100.2" />
      <PackageReference Include="EFCore.NamingConventions" Version="8.0.3" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.22" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.26" />
      <PackageReference Include="g0v0.osu.Game" Version="2026.713.0" />
      <PackageReference Include="ppy.osu.Game.Rulesets.Osu" Version="2026.702.1" />
      <PackageReference Include="ppy.osu.Game.Rulesets.Taiko" Version="2026.702.1" />
      <PackageReference Include="ppy.osu.Game.Rulesets.Catch" Version="2026.702.1" />
      <PackageReference Include="ppy.osu.Game.Rulesets.Mania" Version="2026.702.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
      <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
      <PackageReference Include="StackExchange.Redis" Version="2.13.17" />
    </ItemGroup>

</Project>
