// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using g0v0.Server.Common.Database.PostgreSQL;

#nullable disable

namespace g0v0.Server.Common.Database.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSqlDbContext))]
    [Migration("20260820091244_AddMultiplayerRoomEntities")]
    partial class AddMultiplayerRoomEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.Beatmap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("ApproachRate")
                        .HasColumnType("real")
                        .HasColumnName("approach_rate");

                    b.Property<long>("BeatmapSetId")
                        .HasColumnType("bigint")
                        .HasColumnName("beatmap_set_id");

                    b.Property<int>("BeatmapVersion")
                        .HasColumnType("integer")
                        .HasColumnName("beatmap_version");

                    b.Property<float>("Bpm")
                        .HasColumnType("real")
                        .HasColumnName("bpm");

                    b.Property<string>("Checksum")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("checksum");

                    b.Property<float>("CircleSize")
                        .HasColumnType("real")
                        .HasColumnName("circle_size");

                    b.Property<int>("CirclesCount")
                        .HasColumnType("integer")
                        .HasColumnName("circles_count");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<double>("DifficultyRating")
                        .HasColumnType("double precision")
                        .HasColumnName("difficulty_rating");

                    b.Property<int>("HitLength")
                        .HasColumnType("integer")
                        .HasColumnName("hit_length");

                    b.Property<float>("HpDrainRate")
                        .HasColumnType("real")
                        .HasColumnName("hp_drain_rate");

                    b.Property<DateTimeOffset?>("LastUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_update");

                    b.Property<int>("MapperId")
                        .HasColumnType("integer")
                        .HasColumnName("mapper_id");

                    b.Property<int?>("MaxCombo")
                        .HasColumnType("integer")
                        .HasColumnName("max_combo");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<float>("OverallDifficulty")
                        .HasColumnType("real")
                        .HasColumnName("overall_difficulty");

                    b.Property<int>("SlidersCount")
                        .HasColumnType("integer")
                        .HasColumnName("sliders_count");

                    b.Property<int>("SpinnersCount")
                        .HasColumnType("integer")
                        .HasColumnName("spinners_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalLength")
                        .HasColumnType("integer")
                        .HasColumnName("total_length");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("url");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_beatmaps");

                    b.ToTable("beatmaps", (string)null);
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.OAuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("access_token");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTimeOffset>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scope");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("token_type");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_oauth_tokens");

                    b.HasIndex("AccessToken")
                        .IsUnique()
                        .HasDatabaseName("ix_oauth_tokens_access_token");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_oauth_tokens_client_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_oauth_tokens_expires_at");

                    b.HasIndex("RefreshToken")
                        .IsUnique()
                        .HasDatabaseName("ix_oauth_tokens_refresh_token");

                    b.HasIndex("RefreshTokenExpiresAt")
                        .HasDatabaseName("ix_oauth_tokens_refresh_token_expires_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_oauth_tokens_user_id");

                    b.ToTable("oauth_tokens", (string)null);
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.Playlist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AllowedMods")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allowed_mods");

                    b.Property<int>("BeatmapId")
                        .HasColumnType("integer")
                        .HasColumnName("beatmap_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Expired")
                        .HasColumnType("boolean")
                        .HasColumnName("expired");

                    b.Property<bool>("Freestyle")
                        .HasColumnType("boolean")
                        .HasColumnName("freestyle");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset?>("PlayedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("played_at");

                    b.Property<int>("PlaylistOrder")
                        .HasColumnType("integer")
                        .HasColumnName("playlist_order");

                    b.Property<string>("RequiredMods")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("required_mods");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<int>("RulesetId")
                        .HasColumnType("integer")
                        .HasColumnName("ruleset_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("WinCondition")
                        .HasColumnType("integer")
                        .HasColumnName("win_condition");

                    b.HasKey("Id")
                        .HasName("pk_playlists");

                    b.HasIndex("BeatmapId")
                        .HasDatabaseName("ix_playlists_beatmap_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_playlists_owner_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_playlists_room_id");

                    b.ToTable("playlists", (string)null);
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.Relationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TargetId")
                        .HasColumnType("integer")
                        .HasColumnName("target_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_relationship");

                    b.HasIndex("TargetId")
                        .HasDatabaseName("ix_relationship_target_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_relationship_user_id");

                    b.ToTable("relationship", (string)null);
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AutoSkip")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_skip");

                    b.Property<int>("AutoStartDuration")
                        .HasColumnType("integer")
                        .HasColumnName("auto_start_duration");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<int>("ChannelId")
                        .HasColumnType("integer")
                        .HasColumnName("channel_id");

                    b.Property<DateTimeOffset?>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<int?>("HostId")
                        .HasColumnType("integer")
                        .HasColumnName("host_id");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<byte?>("MaxParticipants")
                        .HasColumnType("smallint")
                        .HasColumnName("max_participants");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("ParticipantCount")
                        .HasColumnType("integer")
                        .HasColumnName("participant_count");

                    b.Property<string>("Password")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("password");

                    b.Property<string>("QueueMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("queue_mode");

                    b.Property<DateTimeOffset?>("StartsAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<bool>("TournamentMode")
                        .HasColumnType("boolean")
                        .HasColumnName("tournament_mode");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_rooms_category");

                    b.HasIndex("HostId")
                        .HasDatabaseName("ix_rooms_host_id");

                    b.HasIndex("Id")
                        .HasDatabaseName("ix_rooms_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_rooms_name");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.RoomParticipatedUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<long>("RoomId")
                        .HasColumnType("bigint")
                        .HasColumnName("room_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_room_participated_users");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_room_participated_users_room_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_room_participated_users_user_id");

                    b.ToTable("room_participated_users", (string)null);
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.Score", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy");

                    b.Property<string>("BeatmapChecksum")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("beatmap_checksum");

                    b.Property<int>("BeatmapId")
                        .HasColumnType("integer")
                        .HasColumnName("beatmap_id");

                    b.Property<long>("ClassicTotalScore")
                        .HasColumnType("bigint")
                        .HasColumnName("classic_total_score");

                    b.Property<long>("ClassicTotalScoreWithoutMods")
                        .HasColumnType("bigint")
                        .HasColumnName("classic_total_score_without_mods");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("")
                        .HasColumnName("client_version");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<bool>("HasReplay")
                        .HasColumnType("boolean")
                        .HasColumnName("has_replay");

                    b.Property<int>("MaxCombo")
                        .HasColumnType("integer")
                        .HasColumnName("max_combo");

                    b.Property<string>("MaximumStatistics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("maximum_statistics");

                    b.Property<int>("Mode")
                        .HasColumnType("integer")
                        .HasColumnName("mode");

                    b.Property<string>("Mods")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("mods");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<long?>("PlaylistItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("playlist_item_id");

                    b.Property<double>("Pp")
                        .HasColumnType("double precision")
                        .HasColumnName("pp");

                    b.Property<bool>("Preserve")
                        .HasColumnType("boolean")
                        .HasColumnName("preserve");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean")
                        .HasColumnName("processed");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<bool>("Ranked")
                        .HasColumnType("boolean")
                        .HasColumnName("ranked");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Statistics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("statistics");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.Property<int>("TotalScoreWithoutMods")
                        .HasColumnType("integer")
                        .HasColumnName("total_score_without_mods");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_scores");

                    b.HasIndex(new[] { "UserId", "Mode", "EndedAt", "Id" }, "idx_score_user_mode_date")
                        .HasDatabaseName("ix_scores_user_id_mode_ended_at_id");

                    b.HasIndex(new[] { "UserId", "Mode", "Pp", "Id" }, "idx_score_user_mode_pp")
                        .HasDatabaseName("ix_scores_user_id_mode_pp_id");

                    b.HasIndex(new[] { "BeatmapId" }, "ix_scores_beatmap_id")
                        .HasDatabaseName("ix_scores_beatmap_id");

                    b.HasIndex(new[] { "Mode" }, "ix_scores_gamemode")
                        .HasDatabaseName("ix_scores_mode");

                    b.HasIndex(new[] { "BeatmapChecksum" }, "ix_scores_map_md5")
                        .HasDatabaseName("ix_scores_beatmap_checksum");

                    b.HasIndex(new[] { "UserId" }, "ix_scores_user_id")
                        .HasDatabaseName("ix_scores_user_id");

                    b.ToTable("scores", (string)null);
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.ScoreToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BeatmapId")
                        .HasColumnType("integer")
                        .HasColumnName("beatmap_id");

                    b.Property<string>("ClientVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("PlaylistItemId")
                        .HasColumnType("integer")
                        .HasColumnName("playlist_item_id");

                    b.Property<int?>("RoomId")
                        .HasColumnType("integer")
                        .HasColumnName("room_id");

                    b.Property<int>("RulesetId")
                        .HasColumnType("integer")
                        .HasColumnName("ruleset_id");

                    b.Property<long?>("ScoreId")
                        .HasColumnType("bigint")
                        .HasColumnName("score_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_score_tokens");

                    b.HasIndex("BeatmapId")
                        .HasDatabaseName("ix_score_tokens_beatmap_id");

                    b.HasIndex("ScoreId")
                        .HasDatabaseName("ix_score_tokens_score_id");

                    b.HasIndex(new[] { "PlaylistItemId", "RoomId" }, "idx_playlist_room")
                        .HasDatabaseName("ix_score_tokens_playlist_item_id_room_id");

                    b.HasIndex(new[] { "UserId", "PlaylistItemId" }, "idx_user_playlist")
                        .HasDatabaseName("ix_score_tokens_user_id_playlist_item_id");

                    b.ToTable("score_tokens", (string)null);
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bot");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<bool>("IsSupporter")
                        .HasColumnType("boolean")
                        .HasColumnName("is_supporter");

                    b.Property<DateTimeOffset?>("LastVisit")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_visit");

                    b.Property<bool>("PmFriendsOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("pm_friends_only");

                    b.Property<string>("ProfileColour")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("profile_colour");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CountryCode")
                        .HasDatabaseName("ix_users_country_code");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.OAuthToken", b =>
                {
                    b.HasOne("g0v0.Server.Common.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_oauth_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.Playlist", b =>
                {
                    b.HasOne("g0v0.Server.Common.Database.Models.Beatmap", "Beatmap")
                        .WithMany()
                        .HasForeignKey("BeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlists_beatmaps_beatmap_id");

                    b.HasOne("g0v0.Server.Common.Database.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlists_users_owner_id");

                    b.HasOne("g0v0.Server.Common.Database.Models.Room", "Room")
                        .WithMany("Playlists")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_playlists_rooms_room_id");

                    b.Navigation("Beatmap");

                    b.Navigation("Owner");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.Relationship", b =>
                {
                    b.HasOne("g0v0.Server.Common.Database.Models.User", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relationship_users_target_id");

                    b.HasOne("g0v0.Server.Common.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relationship_users_user_id");

                    b.Navigation("Target");

                    b.Navigation("User");
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.Room", b =>
                {
                    b.HasOne("g0v0.Server.Common.Database.Models.User", "Host")
                        .WithMany()
                        .HasForeignKey("HostId")
                        .HasConstraintName("fk_rooms_users_host_id");

                    b.Navigation("Host");
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.RoomParticipatedUser", b =>
                {
                    b.HasOne("g0v0.Server.Common.Database.Models.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_participated_users_rooms_room_id");

                    b.HasOne("g0v0.Server.Common.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_participated_users_users_user_id");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.ScoreToken", b =>
                {
                    b.HasOne("g0v0.Server.Common.Database.Models.Beatmap", "Beatmap")
                        .WithMany()
                        .HasForeignKey("BeatmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_score_tokens_beatmaps_beatmap_id");

                    b.HasOne("g0v0.Server.Common.Database.Models.Score", "Score")
                        .WithMany()
                        .HasForeignKey("ScoreId")
                        .HasConstraintName("fk_score_tokens_scores_score_id");

                    b.HasOne("g0v0.Server.Common.Database.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_score_tokens_users_user_id");

                    b.Navigation("Beatmap");

                    b.Navigation("Score");

                    b.Navigation("User");
                });

            modelBuilder.Entity("g0v0.Server.Common.Database.Models.Room", b =>
                {
                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
